def get_tokens():
	return _tokens

def get_inverse_tokens():
	flipped = dict()
	for key in _tokens:
		flipped[_tokens[key]] = key

	return flipped

_tokens = dict([
	# ('>DMS', '\x01'),
	# ('>Dec', '\x02'),
	# ('>Frac', '\x03'),
	('→', ' = '),
	('->', ' = '),
	# ('BoxPlot', '\x05'),
	# ('[', '\x06'),
	# (']', '\x07'),
	# ('{', '\x08'),
	# ('}', '\x09'),
	# ('°', '\x0B'),
	# ('^-1', '\x0C'),
	# ('^2', '\x0D'),
	# ('^T', '\x0E'),
	# ('^3', '\x0F'),
	# ('(', '\x10'),
	# (')', '\x11'),
	# ('round(', '\x12'),
	# ('pxl-Test(', '\x13'),
	# ('augment(', '\x14'),
	# ('rowSwap(', '\x15'),
	# ('row+(', '\x16'),
	# ('*row(', '\x17'),
	# ('*row+(', '\x18'),
	# ('max(', '\x19'),
	# ('min(', '\x1A'),
	# ('R>Pr(', '\x1B'),
	# ('R>P[theta](', '\x1C'),
	# ('P>Rx(', '\x1D'),
	# ('P>Ry(', '\x1E'),
	# ('median(', '\x1F'),
	# ('randM(', '\x20'),
	# ('mean(', '\x21'),
	# ('solve(', '\x22'),
	# ('seq(', '\x23'),
	# ('fnInt(', '\x24'),
	# ('nDeriv(', '\x25'),
	# ('fMin(', '\x27'),
	# ('fMax(', '\x28'),
	# (' ', '\x29'),
	# ('"', '\x2A'),
	# (',', '\x2B'),
	# ('imaginary', '\x2C'),
	# ('!', '\x2D'),
	# ('CubicReg ', '\x2E'),
	# ('QuartReg ', '\x2F'),
	# ('.', '\x3A'),
	# # Alternate notation of E
	# ('10^', '\x3B'),
	# (' or ', '\x3C'),
	# (' xor ', '\x3D'),
	# (':', '\x3E'),
	# ('\n', '\x3F'),
	# (' and ', '\x40'),
	# ('A', '\x41'),
	# ('B', '\x42'),
	# ('C', '\x43'),
	# ('D', '\x44'),
	# ('E', '\x45'),
	# ('F', '\x46'),
	# ('G', '\x47'),
	# ('H', '\x48'),
	# ('I', '\x49'),
	# ('J', '\x4A'),
	# ('K', '\x4B'),
	# ('L', '\x4C'),
	# ('M', '\x4D'),
	# ('N', '\x4E'),
	# ('O', '\x4F'),
	# ('P', '\x50'),
	# ('Q', '\x51'),
	# ('R', '\x52'),
	# ('S', '\x53'),
	# ('T', '\x54'),
	# ('U', '\x55'),
	# ('V', '\x56'),
	# ('W', '\x57'),
	# ('X', '\x58'),
	# ('Y', '\x59'),
	# ('Z', '\x5A'),
	# ('0', '\x30'),
	# ('1', '\x31'),
	# ('2', '\x32'),
	# ('3', '\x33'),
	# ('4', '\x34'),
	# ('5', '\x35'),
	# ('6', '\x36'),
	# ('7', '\x37'),
	# ('8', '\x38'),
	# ('9', '\x39'),
	# ('[theta]', '\x5B'),
	# # System variables (incomplete: TODO)
	# ('[A]', '\x5C\x00'),
	# ('[B]', '\x5C\x01'),
	# ('[C]', '\x5C\x02'),
	# ('[D]', '\x5C\x03'),
	# ('[E]', '\x5C\x04'),
	# ('[F]', '\x5C\x05'),
	# ('[G]', '\x5C\x06'),
	# ('[H]', '\x5C\x07'),
	# ('[I]', '\x5C\x08'),
	# ('[J]', '\x5C\x09'),
	# ('l1', '\x5D\x00'),
	# ('l2', '\x5D\x01'),
	# ('l3', '\x5D\x02'),
	# ('l4', '\x5D\x03'),
	# ('l5', '\x5D\x04'),
	# ('l6', '\x5D\x05'),
	# ('l7', '\x5D\x06'),
	# ('l8', '\x5D\x07'),
	# ('l0', '\x5D\x08'),
	# ('y1', '\x5E\x10'),
	# ('y2', '\x5E\x11'),
	# ('y3', '\x5E\x12'),
	# ('y4', '\x5E\x13'),
	# ('y5', '\x5E\x14'),
	# ('y6', '\x5E\x15'),
	# ('y7', '\x5E\x16'),
	# ('y8', '\x5E\x17'),
	# ('y9', '\x5E\x18'),
	# ('y0', '\x5E\x19'),
	# ('r_1', '\x5E\x40'),
	# ('r_2', '\x5E\x41'),
	# ('r_3', '\x5E\x42'),
	# ('r_4', '\x5E\x43'),
	# ('r_5', '\x5E\x44'),
	# ('r_6', '\x5E\x45'),
	# ('x1t', '\x5E\x20'),
	# ('y1t', '\x5E\x21'),
	# ('x2t', '\x5E\x22'),
	# ('y2t', '\x5E\x23'),
	# ('x3t', '\x5E\x24'),
	# ('y3t', '\x5E\x25'),
	# ('x4t', '\x5E\x26'),
	# ('y4t', '\x5E\x27'),
	# ('x5t', '\x5E\x28'),
	# ('y5t', '\x5E\x29'),
	# ('x6t', '\x5E\x2A'),
	# ('y6t', '\x5E\x2B'),
	# ('prgm', '\x5F'),
	# ('Pic1', '\x60\x00'),
	# ('Pic2', '\x60\x01'),
	# ('Pic3', '\x60\x02'),
	# ('Pic4', '\x60\x03'),
	# ('Pic5', '\x60\x04'),
	# ('Pic6', '\x60\x05'),
	# ('Pic7', '\x60\x06'),
	# ('Pic8', '\x60\x07'),
	# ('Pic9', '\x60\x08'),
	# ('Pic0', '\x60\x09'),
	# ('GDB1', '\x61\x00'),
	# ('GDB2', '\x61\x01'),
	# ('GDB3', '\x61\x02'),
	# ('GDB4', '\x61\x03'),
	# ('GDB5', '\x61\x04'),
	# ('GDB6', '\x61\x05'),
	# ('GDB7', '\x61\x06'),
	# ('GDB8', '\x61\x07'),
	# ('GDB9', '\x61\x08'),
	# ('GDB0', '\x61\x09'),
	# ('RegEq', '\x62\x01'),
	# ('[x-bar]', '\x62\x03'),
	# ('[Summ x]', '\x62\x04'),
	# ('[Summ x^2]', '\x62\x05'),
	# ('Sx', '\x62\x06'),
	# ('[sigma]x', '\x62\x07'),
	# ('minX', '\x62\x08'),
	# ('maxX', '\x62\x09'),
	# ('minY', '\x62\x0A'),
	# ('maxY', '\x62\x0B'),
	# ('[y-bar]', '\x62\x0C'),
	# ('[Summ y]', '\x62\x0D'),
	# ('[Summ y^2]', '\x62\x0E'),
	# ('Sy', '\x62\x0F'),
	# ('[sigma]y', '\x62\x10'),
	# ('[Summ xy]', '\x62\x11'),
	# ('Med', '\x62\x13'),
	# ('Q1', '\x62\x14'),
	# ('Q3', '\x62\x15'),
	# ('x1', '\x62\x1B'),
	# ('x2', '\x62\x1C'),
	# ('x3', '\x62\x1D'),
	# ('y1', '\x62\x1E'),
	# ('y2', '\x62\x1F'),
	# ('y3', '\x62\x20'),
	# ('[chi]2', '\x62\x25'),
	# ('[fin]', '\x62\x26'),
	# ('df', '\x62\x27'),
	# ('[p-hat]', '\x62\x28'),
	# ('[p-hat]1', '\x62\x29'),
	# ('[p-hat]2', '\x62\x2A'),
	# ('[x-bar]1', '\x62\x2B'),
	# ('Sx1', '\x62\x2C'),
	# ('n_1', '\x62\x2D'),
	# ('[x-bar]2', '\x62\x2E'),
	# ('Sx2', '\x62\x2F'),
	# ('n_2', '\x62\x30'),
	# ('Sxp', '\x62\x31'),
	# ('lower', '\x62\x32'),
	# ('upper', '\x62\x33'),
	# ('r2', '\x62\x35'),
	# ('R2', '\x62\x36'),
	# ('SS', '\x62\x38'),
	# ('MS', '\x62\x39'),
	# ('ZXscl', '\x63\x00'),
	# ('ZYscl', '\x63\x01'),
	# ('Xscl', '\x63\x02'),
	# ('Yscl', '\x63\x03'),
	# ('U_nStart', '\x63\x04'),
	# ('V_nStart', '\x63\x05'),
	# ('U_(n-1)', '\x63\x06'),
	# ('V_(n-1)', '\x63\x07'),
	# ('Radian', '\x64'),
	# ('Degree', '\x65'),
	# ('Normal', '\x66'),
	# ('Sci', '\x67'),
	# ('Eng', '\x68'),
	# ('Float', '\x69'),
	# ('=', '\x6A'),
	# ('<', '\x6B'),
	# ('>', '\x6C'),
	# ('<=', '\x6D'),
	# ('>=', '\x6E'),
	# ('!=', '\x6F'),
	# ('+', '\x70'),
	# ('–', '\x71'),
	# ('Ans', '\x72'),
	# ('Fix ', '\x73'),
	# ('Horiz', '\x74'),
	# ('Full', '\x75'),
	# ('Func', '\x76'),
	# ('Param', '\x77'),
	# ('Polar', '\x78'),
	# ('Seq', '\x79'),
	# ('IndpntAuto', '\x7A'),
	# ('IndpntAsk', '\x7B'),
	# ('DependAuto', '\x7C'),
	# ('DependAsk', '\x7D'),
	# # 73 ** (Graph Options)
	# ('Sequential', '\x7E\x00'),
	# ('Simul', '\x7E\x01'),
	# ('PolarGC', '\x7E\x02'),
	# ('RectGC', '\x7E\x03'),
	# ('CoordOn', '\x7E\x04'),
	# ('CoordOff', '\x7E\x05'),
	# ('Connected', '\x7E\x06'),
	# ('Dot', '\x7E\x07'),
	# ('AxesOn', '\x7E\x08'),
	# ('AxesOff', '\x7E\x09'),
	# ('GridOn', '\x7E\x0A'),
	# ('GridOff', '\x7E\x0B'),
	# ('LabelOn', '\x7E\x0C'),
	# ('LabelOff', '\x7E\x0D'),
	# ('Web', '\x7E\x0E'),
	# ('Time', '\x7E\x0F'),
	# ('uvAxes', '\x7E\x10'),
	# ('vwAxes', '\x7E\x11'),
	# ('uwAxes', '\x7E\x12'),
	# # End of 7E Options
	# ('[box]', '\x7F'),
	# ('[cross]', '\x80'),
	# ('[dot]', '\x81'),
	# ('*', '\x82'),
	# ('/', '\x83'),
	# ('Trace', '\x84'),
	# ('ClrDraw', '\x85'),
	# ('ZStandard', '\x86'),
	# ('ZTrig', '\x87'),
	# ('ZBox', '\x88'),
	# ('Zoom_In', '\x89'),
	# ('Zoom_Out', '\x8A'),
	# ('ZSquare', '\x8B'),
	# ('ZInteger', '\x8C'),
	# ('ZPrevious', '\x8D'),
	# ('ZDecimal', '\x8E'),
	# ('ZoomStat', '\x8F'),
	# ('ZoomRcl', '\x90'),
	# ('PrintScreen', '\x91'),
	# ('ZoomSto', '\x92'),
	# ('Text(', '\x93'),
	# (' nPr ', '\x94'),
	# (' nCr ', '\x95'),
	# ('FnOn ', '\x96'),
	# ('FnOff ', '\x97'),
	# ('StorePic ', '\x98'),
	# ('RecallPic ', '\x99'),
	# ('StoreGDB ', '\x9A'),
	# ('RecallGDB ', '\x9B'),
	# ('Line(', '\x9C'),
	# ('Vertical ', '\x9D'),
	# ('Pt-On(', '\x9E'),
	# ('Pt-Off(', '\x9F'),
	# ('Pt-Change( ', '\xA0'),
	# ('Pxl-On( ', '\xA1'),
	# ('Pxl-Off( ', '\xA2'),
	# ('Pxl-Change( ', '\xA3'),
	# ('Shade(', '\xA4'),
	# ('Circle(', '\xA5'),
	# ('Horizontal ', '\xA6'),
	# ('Tangent(', '\xA7'),
	# ('DrawInv ', '\xA8'),
	# ('DrawF ', '\xA9'),
	# # System variables (TODO)
	# ('Str1', '\xAA\x00'),
	# ('Str2', '\xAA\x01'),
	# ('Str3', '\xAA\x02'),
	# ('Str4', '\xAA\x03'),
	# ('Str5', '\xAA\x04'),
	# ('Str6', '\xAA\x05'),
	# ('Str7', '\xAA\x06'),
	# ('Str8', '\xAA\x07'),
	# ('Str9', '\xAA\x08'),
	# ('Str0', '\xAA\x09'),
	# ('rand', '\xAB'),
	# ('[pi]', '\xAC'),
	# ('getKey', '\xAD'),
	# ('\'', '\xAE'),
	# ('?', '\xAF'),
	# ('-', '\xB0'),
	# ('int(', '\xB1'),
	# ('abs(', '\xB2'),
	# ('det(', '\xB3'),
	# ('identity(', '\xB4'),
	# ('dim(', '\xB5'),
	# ('sum(', '\xB6'),
	# ('prod(', '\xB7'),
	# ('not(', '\xB8'),
	# ('iPart(', '\xB9'),
	# ('fPart(', '\xBA'),
	# # BB tokens (two-byte), Incomplete TODO
	# ('npv(', '\xBB\x00'),
	# ('irr(', '\xBB\x01'),
	# ('bal(', '\xBB\x02'),
	# ('SummPrn(', '\xBB\x03'),
	# ('SummInt(', '\xBB\x04'),
	# ('>Nom(', '\xBB\x05'),
	# ('>Eff(', '\xBB\x06'),
	# ('dbd(', '\xBB\x07'),
	# ('Icm(', '\xBB\x08'),
	# ('gcd(', '\xBB\x09'),
	# ('randInt(', '\xBB\x0A'),
	# ('randBin(', '\xBB\x0B'),
	# ('sub(', '\xBB\x0C'),
	# ('stdDev(', '\xBB\x0D'),
	# ('variance(', '\xBB\x0E'),
	# ('inString(', '\xBB\x0F'),
	# ('a', '\xBB\xB0'),
	# ('b', '\xBB\xB1'),
	# ('c', '\xBB\xB2'),
	# ('d', '\xBB\xB3'),
	# ('e', '\xBB\xB4'),
	# ('f', '\xBB\xB5'),
	# ('g', '\xBB\xB6'),
	# ('h', '\xBB\xB7'),
	# ('i', '\xBB\xB8'),
	# ('j', '\xBB\xB9'),
	# ('k', '\xBB\xBA'),
	# ('l', '\xBB\xBC'),
	# ('m', '\xBB\xBD'),
	# ('n', '\xBB\xBE'),
	# ('o', '\xBB\xBF'),
	# ('p', '\xBB\xC0'),
	# ('q', '\xBB\xC1'),
	# ('r', '\xBB\xC2'),
	# ('s', '\xBB\xC3'),
	# ('t', '\xBB\xC4'),
	# ('u', '\xBB\xC5'),
	# ('v', '\xBB\xC6'),
	# ('w', '\xBB\xC7'),
	# ('x', '\xBB\xC8'),
	# ('y', '\xBB\xC9'),
	# ('z', '\xBB\xCA'),
	# # end of xBB
	# ('sqrt(', '\xBC'),
	# ('cubrt(', '\xBD'),
	# ('ln (', '\xBE'),
	# ('e^(', '\xBF'),
	# ('log(', '\xC0'),
	# ('10^(', '\xC1'),
	# ('sin(', '\xC2'),
	# ('sin^-1(', '\xC3'),
	# ('cos(', '\xC4'),
	# ('cos^-1(', '\xC5'),
	# ('tan(', '\xC6'),
	# ('tan^-1(', '\xC7'),
	# ('sinh(', '\xC8'),
	# ('sinh^-1(', '\xC9'),
	# ('cosh(', '\xCA'),
	# ('cosh^-1(', '\xCB'),
	# ('tanh(', '\xCC'),
	# ('tanh^-1(', '\xCD'),
	# ('If ', '\xCE'),
	# ('Then', '\xCF'),
	# ('Else', '\xD0'),
	# ('While ', '\xD1'),
	# ('Repeat ', '\xD2'),
	# ('For ', '\xD3'),
	# ('End', '\xD4'),
	# ('Return', '\xD5'),
	# ('Lbl ', '\xD6'),
	# ('Goto ', '\xD7'),
	# ('Pause ', '\xD8'),
	# ('Stop', '\xD9'),
	# ('IS>(', '\xDA'),
	# ('DS>(', '\xDB'),
	# ('Input ', '\xDC'),
	# ('Prompt ', '\xDD'),
	('Disp (.*[^)])', 'print(\1)'),
	# ('DispGraph', '\xDF'),
	# ('Output(', '\xE0'),
	# ('ClrHome', '\xE1'),
	# ('Fill(', '\xE2'),
	# ('SortA(', '\xE3'),
	# ('SortD(', '\xE4'),
	# ('DispTable', '\xE5'),
	# ('Menu(', '\xE6'),
	# ('Send(', '\xE7'),
	# ('Get(', '\xE8'),
	# ('PlotsOn ', '\xE9'),
	# ('PlotsOff ', '\xEA'),
	# ('Plot1(', '\xEC'),
	# ('Plot2(', '\xED'),
	# ('Plot3(', '\xEE'),
	# ('^', '\xF0'),
	# ('[xth root]', '\xF1'),
	# ('1-Var Stats ', '\xF2'),
	# ('2-Var Stats ', '\xF3'),
	# ('LinReg(a+bx) ', '\xF4'),
	# ('ExpReg ', '\xF5'),
	# ('LnReg ', '\xF6'),
	# ('PwrReg ', '\xF7'),
	# ('Med-Med ', '\xF8'),
	# ('QuadReg ', '\xF9'),
	# ('ClrList ', '\xFA'),
	# ('ClrTable', '\xFB'),
	# ('Histogram', '\xFC'),
	# ('xyLine', '\xFD'),
	# ('Scatter', '\xFE'),
	# ('LinReg(ax+b) ', '\xFF'),
	# ('Textcolor(', '\xEF\x67'),
	# ('BackgroundOn ', '\xEF\x5B'),
	# ('BLUE', '\xEF\x41'),
	# ('RED', '\xEF\x42'),
	# ('BLACK', '\xEF\x43'),
	# ('MAGENTA', '\xEF\x44'),
	# ('GREEN', '\xEF\x45'),
	# ('ORANGE', '\xEF\x46'),
	# ('BROWN', '\xEF\x47'),
	# ('NAVY', '\xEF\x48'),
	# ('LTBLUE', '\xEF\x49'),
	# ('YELLOW', '\xEF\x4A'),
	# ('WHITE', '\xEF\x4B'),
	# ('LTGRAY', '\xEF\x4C'),
	# ('MEDGRAY', '\xEF\x4D'),
	# ('GRAY', '\xEF\x4E'),
	# ('DRAKGRAY', '\xEF\x4F'),
	# ('getDate', '\xEF\x09'),
	# ('getTime', '\xEF\x0A'),
	# ('dayOfWk(', '\xEF\x06'),
	# ('ClrAllLists', '\xBB\x52'),
	# ('BackgroundOff', '\xEF\x64'),
	# ('remainder(', '\xEF\x32'),
	# ('BorderColor ', '\xEF\x6C'),
	# ('MATHPRINT', '\xEF\x37'),
	# ('AUTO', '\xEF\x3B'),
	# ('[n/d]', '\xEF\x39'),
	# ('a+bi', '\xBB\x4F'),
	# ('Thick', '\x7E\x06'),
	# ('ClockOn', '\xEF\x10'),
	# ('ClockOff', '\xEF\x0F'),
	# ('Wait ', '\xEF\x96'),
	# ('CLASSIC', '\xEF\x38'),
	# ('Dot-Thin', '\xEF\x75'),
	# ('Real', '\xBB\x4D'),
	# ('[Un/d]', '\xEF\x3A'),
	# ('DiagnosticOff', '\xBB\x67'),
	# ('STARTWIZARD OFF', '\xEF\x40'),
	# ('ExprOff', '\xBB\x51'),
	# ('DetectAsymOff', '\xEF\x6B'),
	# ('DetectAsymOn', '\xEF\x6A'),
	# ('DiagnosticOn', '\xBB\x66'),
	# ('STARTWIZARD ON', '\xEF\x3F'),
	# ('ExprOn', '\xBB\x50')
])